administrator/components/com_users/config.xml, installation/sql/mysql/joomla.sql, installation/sql/mysql/sample_testing.sql, media/system/js/core-uncompressed.js, tests/system/resetdb.sql, tests/unit/stubs/database/jos_assets.csv, tests/unit/suites/libraries/joomla/utilities/stubs/test.xml
=> Remove references to com_massmail

composer.json, lib/libraries/joomla/archive/tar.php
=> Remove PHP5.5 compatibility

app/bootstrap.php, app/site/components/com_finder/views/search/view.html.php
=> Remove $_PROFILER global

lib/libraries/import.legacy.php, lib/libraries/import.php
=> Register JArrayHelper with the autoloader.

app/administrator/components/com_config/model/component.php, app/administrator/components/com_languages/models/language.php, app/administrator/components/com_menus/models/item.php, app/administrator/components/com_menus/models/menu.php, app/administrator/components/com_modules/models/module.php, app/administrator/components/com_plugins/models/plugin.php, app/administrator/components/com_templates/models/style.php, app/administrator/components/com_users/models/group.php, app/administrator/components/com_users/models/user.php, lib/libraries/legacy/application/application.php, lib/libraries/legacy/model/admin.php
This PR contains the changes that were made in joomla/joomla-cms#4308.
Resolves #245
=> Merged events dispatching inconsistencies fixes

lib/libraries/legacy/model/list.php
This PR resolves #249 by applying the patch from joomla cms v3.4.5. The only core file changed is JModelList, the other patches apply to com_content and com_contenthistory.
=> Backport security fixes from Joomla v3.4.5

lib/libraries/cms/application/cms.php, lib/libraries/joomla/session/session.php
=> Fix session fixation vulnerability

composer.json, composer.lock, config/configuration.php
=> Do not load .env file in production

composer.json, composer.lock
=> Use v2.1.0 as minimum phpdotenv version

app/defines.php, web/administrator/index.php, web/index.php
=> Add JOOMLATOOLS_PLATFORM define 

lib/libraries/cms/version/version.php
=> Keep JVERSION compatible with Joomla

.gitignore
=> Gitignore ignores lib/libraries/joomla/log

.gitignore, COPYRIGHT.md, lib/libraries/cms/version/version.php
=> Complete COPYRIGHT.md

CHANGELOG.md, lib/libraries/cms/version/version.php
=> Release 1.0.3

composer.json, composer.lock, install/mysql/data.sql, install/mysql/migrations/20160303152100_remove_debug_plugin.php, install/mysql/migrations/v1.0.1.sql, install/mysql/schema.sql, phinx.php
=> Add phinx support

lib/plugins/system/languagefilter/languagefilter.php
=> Correct language cookie path

app/administrator/components/com_menus/models/item.php, app/site/components/com_users/models/reset.php, composer.json, composer.lock, lib/libraries/joomla/database/driver/mysqli.php, lib/libraries/joomla/session/session.php, lib/libraries/joomla/uri/uri.php
=> Port security fixes from Joomla v3.4.6 - v3.4.8

app/administrator/modules/mod_menu/tmpl/default.php
Fix the menu for com:users in the backend.
=> Users cannot login to administrator

composer.json, composer.lock, phinx.php
=> Include Phinx migrations from extensions

app/administrator/helper.php
=> Fix time-out error

app/administrator/components/com_users/views/users/tmpl/modal.php
=> Changing author name not working in articles

config/environment.php
=> Disable frontend editing by default

.env.example, config/configuration.php, config/environment.php
=> JOOMLA_CACHE requires integer value

config/environment.php
=> Enable sef_advance_link by default

install/mysql/migrations/v2.0.0/20180301063731_install_plg_system404.php, lib/plugins/system/404/404.php, lib/plugins/system/404/404.xml, lib/plugins/system/404/language/en-GB/en-GB.plg_system_404.ini, lib/plugins/system/404/language/en-GB/en-GB.plg_system_404.sys.ini
=> Create 404 re-direct plugin

install/mysql/data.sql
This will remove the default logo in elysio template parameter in the install.sql
This PR closes #350
=> Remove the default logo in elysio template parameter

web/administrator/templates/elysio/error.php
=> Fix error page in backend template

lib/libraries/cms/model/admin.php, web/administrator/templates/elysio/html/com_modules/modules/default.php
=> Fix sortable behaviour

lib/libraries/cms/installer/adapter/component.php
=> Fix uninstall method for components

CHANGELOG.md
=> Prepare 2.0.1 release #364
